const NUM_DIE_SIDES = 6;
const DICE_PER_PLAYER = 5;
const DEFAULT_NUM_PLAYERS = 3;
const CHALLENGE_SYMBOL = "C";
const PLAYER_TYPES = {
  HUMAN: "human",
  COMPUTER: "computer",
};

module.exports = {
  NUM_DIE_SIDES,
  DICE_PER_PLAYER,
  DEFAULT_NUM_PLAYERS,
  CHALLENGE_SYMBOL,
  PLAYER_TYPES,
};
